#generated by MCBuilder/mc

execute if score output test matches 1..9 run scoreboard players set #precision math_const 100000000
execute if score output test matches 1..9 run scoreboard players set #decimal math_const 1
execute if score output test matches 10..99 run scoreboard players set #precision math_const 1000000
execute if score output test matches 10..99 run scoreboard players set #decimal math_const 10
execute if score output test matches 100..999 run scoreboard players set #precision math_const 1000000
execute if score output test matches 100..999 run scoreboard players set #decimal math_const 10
execute if score output test matches 1000..9999 run scoreboard players set #precision math_const 10000
execute if score output test matches 1000..9999 run scoreboard players set #decimal math_const 100
execute if score output test matches 10000..99999 run scoreboard players set #precision math_const 10000
execute if score output test matches 10000..99999 run scoreboard players set #decimal math_const 100
execute if score output test matches 100000..999999 run scoreboard players set #precision math_const 100
execute if score output test matches 100000..999999 run scoreboard players set #decimal math_const 1000
execute if score output test matches 1000000..9999999 run scoreboard players set #precision math_const 100
execute if score output test matches 1000000..9999999 run scoreboard players set #decimal math_const 1000
execute if score output test matches 10000000..99999999 run scoreboard players set #precision math_const 1
execute if score output test matches 10000000..99999999 run scoreboard players set #decimal math_const 10000
execute if score output test matches 100000000..999999999 run scoreboard players set #precision math_const 1
execute if score output test matches 100000000..999999999 run scoreboard players set #decimal math_const 10000
scoreboard players operation input_process math_temp = output test
scoreboard players operation input_process math_temp *= #precision math_const
scoreboard players set const2 math_const 2
scoreboard players set output test 1
function test:__generated__/block/2