#generated by MCBuilder/mc

scoreboard players operation const4 math_const = distance output
scoreboard players operation const3 math_const = input_process math_temp
scoreboard players operation const3 math_const /= distance output
scoreboard players operation distance output += const3 math_const
scoreboard players operation distance output /= const2 math_const
scoreboard players operation const4 math_const -= distance output
execute unless score const4 math_const matches -1..1 run function test:__generated__/block/0