#generated by MCBuilder/mc

scoreboard players operation const4 math_const = output test
scoreboard players operation const3 math_const = input_process math_temp
scoreboard players operation const3 math_const /= output test
scoreboard players operation output test += const3 math_const
scoreboard players operation output test /= const2 math_const
scoreboard players operation const4 math_const -= output test
execute unless score const4 math_const matches -1..1 run function test:__generated__/block/2