#generated by MCBuilder/mc

tellraw @a {"text":"Invalid input for macro math_sqrt in test:__generated__/block/3","color":"red","bold":true}
tellraw @a {"text":"This message will not appear in production","color":"red"}