#generated by MCBuilder/mc

scoreboard players set scale math_const 1
scoreboard players operation output test = value test
execute unless score output test matches ..0 run function test:__generated__/execute/2
scoreboard players operation output test *= #decimal math_const
scoreboard players operation output test *= scale math_const
execute if score output test matches ..-1 run function test:__generated__/execute/3