//generated config
module.exports = {
  "mc": {
    "dev": true,
    "header": "#generated by MCBuilder/mc",
    "internalScoreboard": "LANG_MC_INTERNAL",
    "rootNamespace": null,
    "globalMacrosFile": "macros.mc",
    test(a){return a*-1}
  }
}
