#generated by MCBuilder/mc

execute positioned 0 30 50 run fill ~-10 ~ ~-10 ~10 ~ ~10 blue_stained_glass
execute positioned 35 30 35 run fill ~-10 ~ ~-10 ~10 ~ ~10 blue_stained_glass
execute positioned 50 30 0 run fill ~-10 ~ ~-10 ~10 ~ ~10 blue_stained_glass
execute positioned 35 30 -35 run fill ~-10 ~ ~-10 ~10 ~ ~10 blue_stained_glass
execute positioned 0 30 -50 run fill ~-10 ~ ~-10 ~10 ~ ~10 blue_stained_glass
execute positioned -35 30 -35 run fill ~-10 ~ ~-10 ~10 ~ ~10 blue_stained_glass
execute positioned -50 30 0 run fill ~-10 ~ ~-10 ~10 ~ ~10 blue_stained_glass
execute positioned -35 30 35 run fill ~-10 ~ ~-10 ~10 ~ ~10 blue_stained_glass